2024-yju-capston-team3/project_fukuoka-album-deployment-repo

db.json, src/API.ts, src/components/Map/Map.tsx, src/types.ts
`Point` 위치 정보 받아와서 `Marker` 기능 구현 완료
=> feat: Implement marker API

src/App.tsx, src/Layout/Footer.tsx
=> feat: Implement footer

.gitignore
=> refactor: Add db.json

package-lock.json, package.json, public/index.html, public/menu.svg, src/App.tsx, src/components/Header/Header.tsx, src/fonts/font.css
=> feat: 메뉴바 추가 

src/App.tsx, src/Router.tsx
=> feat: Implement router

src/components/Card/CardStyles.ts, src/components/Card/index.tsx, src/components/Map/MapStyles.ts, src/components/Map/index.tsx, src/components/layout/body/BodyStyles.ts, src/components/layout/body/index.css, src/components/layout/body/index.tsx, src/components/layout/footer/FooterStyles.ts, src/components/layout/footer/index.tsx, src/components/layout/header/HeaderStyles.ts, src/components/layout/index.tsx
=> refactor: Modify css structure

src/components/layout/header/index.tsx
=> feat: Implement header routing logic

db.json
=> refactor: Delete db.json

src/components/album/index.tsx, src/types/post.interface.ts
- `Post` 인터페이스 수정
- 고칠 부분 주석 추가
=> Refactor album

src/components/album/index.tsx, src/services/user.service.ts, src/types/post.interface.ts
=> feat: Implement getting user's post logic

src/components/modal/ModalStyles.ts, src/components/modal/index.tsx, src/components/mypage/MyPageStyles.ts
=> style: Modify css logic

src/components/layout/body/BodyStyles.ts, src/components/layout/header/HeaderStyles.ts, src/components/map/MapStyles.ts, src/components/mypage/MyPageStyles.ts
`Header`, `Body`, `Map` css 변경
=> style: Modify css style

package-lock.json, src/components/modal/index.tsx, src/components/mypage/MyPageStyles.ts
- `Card` css 로직 변경
- `updatedUser`에 기입되는 데이터 변경
=> refactor: Refactor mypage

src/App.tsx, src/components/map/index.tsx
=> fix: Modify google maps rendering logic

src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx
- modal 창에서 좋아요와 댓글 아이콘이 비정상적으로 크게 되는 문제를 해결했습니다
=> fix : image issue with Icon resizing

src/components/post/index.tsx, src/services/location.service.ts, src/services/post.service.ts
- `게시글`이 존재하는 경우에만 `Marker`가 찍히도록 로직 개선했습니다.
- `src/components/post/index.tsx`에서 불필요하게 `import`가 구분되어 있어 수정했습니다.
=> refactor: Modify marker logic

src/Router.tsx, src/components/layout/header/index.tsx, src/components/post/modal/index.tsx, src/components/write/index.tsx, src/components/write/writeStyles.ts, src/pages/write/index.tsx
=> feat: add writepage

src/components/album/index.tsx, src/components/mypage/index.tsx, src/components/post/PostStyles.ts, src/components/post/index.tsx, src/types/post.interface.ts
클릭한 이후 표시되는 이미지위에 마우스를 올리면 해당 게시글의 좋아요 개수와 댓글 수를 표시하는 기능을 추가하였습니다
=> feat: Implement like & comment counter

src/components/modal/index.tsx, src/components/mypage/index.tsx, src/components/post/modal/index.tsx, src/services/auth.service.ts
- 글이 없을 때는 글 담아놓는 컴포넌트가 아예 반환되지 않게 수정
- 모달 띄울 때 헤더 어두워지게 수정
=> fix: Add zIndex to overlay

src/components/mypage/index.tsx, src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx, src/services/comment.service.ts, src/types/comment.interface.ts, src/types/post.interface.ts
=> feat : add comment modal component & style

src/components/album/index.tsx, src/components/layout/header/index.tsx, src/components/map/index.tsx, src/components/mypage/index.tsx, src/services/post.service.ts, src/store/index.ts, src/store/search.ts, src/types/post.interface.ts
- `검색` 로직 구현 완료
- 초기 상태에는 `모든 게시글`이 출력되도록 수정
=> feat: Implement searching logic

src/components/modal/index.tsx
=> refactor: Add zIndex in modal

src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx
- 특정 글자수(100자) 및 내용 높이에 따라 더보기를 통해 남은 내용을 확인하는 기능추가
=> feat : add more view & rename Comment to Content

.gitignore, package.json
`package.json`에서 `json-server` 실행 명령어 제거
=> 📦 refactor: Remove unnecessary script

src/components/post/modal/index.tsx, src/services/comment.service.ts, src/types/post.interface.ts
- 댓글의 수를 쉽게 파악하고자 comment id를 배열에 담는 코드를 추가했습니다
=> refactor : Get comment id when add or delete

src/components/post/PostStyles.ts, src/components/post/index.tsx, src/components/post/likeChecked.svg, src/types/post.interface.ts
* `modal` 에서 누른 좋아요가 `post` 에서 실시간으로 반영되지 않고 있던 점을 해결하였습니다.
* `like`와 `comment` 아이콘의 배치 및 개수를 나타내는 폰트,스타일을 조정하였습니다.
=> refactor: Modify likeChecked icon

src/components/album/index.tsx, src/components/post/index.tsx
* 표시되는 포스트의 수를 분할하여 스크롤을 맨 밑으로 내릴 때마다 
추가적인 포스트를 표시하는 기능을 추가하였습니다
* 불필요한 주석을 삭제하였습니다
=> feat: Implement Scrolling

src/components/album/index.tsx
* 스크롤 이벤트를 받아오는 로직에 오류를 발견하여 수정하였습니다
=> fix: Fix scrolling

src/Router.tsx, src/components/layout/header/index.tsx, src/services/api.service.ts, src/services/auth.service.ts, src/services/user.service.ts, tsconfig.json
- api 요청시 인증이 제대로 안이루어지는 부분
- tsconfig 의 target 을 es2015로 수정
=> fix: Fix fetchOptions function

src/Router.tsx
* `router.tsx` 에서 불필요하게 작성된 코드를 삭제하였습니다
=> refactor: Delete unnecessary code

src/services/api.service.ts, src/services/auth.service.ts, src/services/signIn.service.ts, tsconfig.json
=> Refactor: refactor api.services

src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx, src/services/location.service.ts
=> feat : add modal image slide feature

src/components/layout/header/index.tsx, src/components/write/index.tsx, src/components/write/slide/index.tsx, src/components/write/writeStyles.ts, src/services/api.service.ts, src/services/write.service.ts, src/types/post.interface.ts
- image upload 한번에 하지 않고 하나씩 끊어서 요청 하게 수정했습니다.
=> refact: modify uploadPostImage

src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx, src/components/write/writeStyles.ts, src/services/signIn.service.ts, src/services/user.service.ts
- 게시글 모달창 스타일 변경
- `getUser` 와 `updateUser` 서비스 함수의 에러사항을 수정했습니다
=> refactor : Post modal style change

src/components/post/modal/index.tsx, src/services/post.service.ts
* `post` 모달창에서 `삭제` 버튼을 누르면 게시글을 삭제할 수 있는 기능을 추가하였습니다.
=> feat: Add Post Delete

src/components/modal/index.tsx, src/services/api.service.ts, src/services/user.service.ts
- 유저 수정 시 스토어 디스패치
- 사진 삭제 api
=> fix(api): Fix error handling in uploadApi and add deleteImageApi

src/components/post/modal/index.tsx
- 댓글에 대댓글을 작성하고 삭제하고나서, 댓글을 달았을 때 대댓글이 다시 생성되는 버그를 고쳤습니다
=> refactor : Fix bug(reply comment) & code refactor

src/components/mypage/MyPageStyles.ts, src/components/mypage/index.tsx, src/components/write/index.tsx, src/services/api.service.ts, src/services/post.service.ts, src/services/user.service.ts, src/services/write.service.ts
- 게시글 작성 과정에 사진을 업로드 할 시 임시저장소에 저장
- 게시글 작성 시 임시저장소 테이블의 사진을 삭제
- 특정 시간이 지나면 임시저장소에 있는 사진을 조회
- 조회가 된다면 게시글 작성이 이뤄지지 않은 것으로 판단해 해당 사진을 삭제 합니다.
=> feat(api): add deleteTempImageFromDb function

src/components/post/modal/ModalStyles.ts, src/components/post/modal/index.tsx, src/components/write/index.tsx, src/services/post.service.ts, src/services/write.service.ts, src/types/post.interface.ts
- 게시글 수정 기능 추가했습니다.
- 세세한 부분은 아직 테스트 해봐야 합니다.
=> Writing page

src/components/post/modal/ModalStyles.ts, src/components/write/index.tsx, src/services/post.service.ts, src/services/write.service.ts
=> refact: modify imageUpload function & z-index

src/components/write/index.tsx, src/components/write/writeStyles.ts, src/services/write.service.ts
=> refact: modify post editFunction

src/Router.tsx, src/components/layout/header/index.tsx, src/pages/teampage/index.tsx
=> 💄 style: Add team page route and menu item

src/components/memberCard/CardStyles.ts, src/components/memberCard/index.tsx, src/components/modal/member/index.tsx, src/pages/teampage/index.tsx, src/services/member.service.ts, src/store/member.ts, src/types/member.interface.ts, src/types/modal.interface.ts
`멤버 소개 페이지`에 맞게 인터페이스 수정 및 버튼 추가
- 멤버 정보 Get 로직 추가
- 멤버 정보 Add 로직 추가
- 멤버 정보 Delete 로직 추가
=> ✨ feat: Refactor team page component and update member card component

src/pages/teampage/index.tsx, src/services/member.service.ts, src/types/member.interface.ts
- 맴버 생성, 읽어오기, 삭제 함수
- 맴버 타입에서 imageUrl 값을 옵션으로 변경
- 맴버 생성 및 수정에 필요한 타입의 이름 변경
=> feat(service): Implement member service

src/components/modal/member/index.tsx, src/pages/teampage/index.tsx, src/services/member.service.ts, src/types/member.interface.ts
- 디폴트 이미지 추가
- 맴버 추가 시 이미지가 없으면 디폴트 이미지로 생성.
- 맴버 수정시 새롭게 추가하려는 이미지를 포함하도록 수정.
=> refactor: Refactor updateMember

package-lock.json
=> 📦 chore: Remove @react-oauth/google dependency

src/components/memberCard/index.tsx, src/components/modal/addMember/index.tsx, src/components/modal/member/index.tsx, src/pages/teampage/index.tsx, src/services/member.service.ts
=> ✨ feat: Fix typos and update member card component

src/components/modal/post/index.tsx, src/components/post/index.tsx, src/components/write/index.tsx, src/services/write.service.ts, src/types/post.interface.ts
=> refactor: modify editPost

src/components/modal/post/index.tsx, src/components/post/index.tsx
- 좋아요를 체크하지 않아도 표시되는 버그 수정
- 사용하지 않는 변수 삭제
- `Modal` 컴포넌트에 `props` 추가
- 좋아요를 확인하는 상태
=> fix : solve the problem in likeChecked

src/components/mypage/MyPageStyles.ts, src/services/auth.service.ts
- mypage CardContainer margin 넣었습니다.
- 회원 가입시 디폴트 이미지가 적용됩니다.
=> feat(auth.service): add default image URL for user registration

src/services/user.service.ts
- 내 정보에서 내용 변경 시 비밀번호가 사라지는 현상을 `PATCH`로 변경하여 해결했습니다
=> fix : modify user service PUT to PATCH

src/components/write/index.tsx
- modal 창 바깥을 눌렀을 때 게시글 데이터가 남아있는 문제 해결
=> refact: modify writeModal

src/components/write/index.tsx, src/services/write.service.ts
- 두 가지 에러 수정
- 글 쓰기 할 때 이미지가 보이지 않는 현상을 수정 (`api req` 경로를 수정)
- `modal` 창을 열 때 `find` 메소드가 가끔 발생하는 에러를 조건문을 걸어 수정
=> Fix : Not display image & find method Error
